import { useMemo, useState } from 'react';
import { vaultPasswords, type VaultPassword } from '../utils/dashboardData';
import Footer from './layout/Footer';
import Header from './layout/Header';
import MobileNavigation from './layout/MobileNavigation';
import Sidebar from './layout/Sidebar';

type Filter = 'All' | 'Recent' | 'Favourite' | 'Last Edit';

function PasswordRow({ password, selected, onSelect, onToggleFavorite, onDelete }: { password: VaultPassword; selected: boolean; onSelect: () => void; onToggleFavorite: () => void; onDelete: () => void }) {
  const iconClass = password.tone === 'dark' ? 'bg-[#171717] text-white' : password.tone === 'blue' ? 'bg-linear-to-br from-[#3d5bf4] to-[#55b5ff] text-white' : password.service === 'Coursera' ? 'bg-[#eef2f5] text-[#0c58ca]' : password.service === 'Netflix' ? 'bg-[#eef2f5] text-[#d10e1c]' : password.service === 'Udemy' ? 'bg-[#eef2f5] font-serif italic text-[#ed4b58]' : 'bg-[#eef2f5] text-[#e94435]';
  return <article className={`flex items-center gap-[14px] rounded-[14px] border border-transparent bg-[#f8f9fb] px-[14px] py-3 hover:border-[#f5c5d8] hover:bg-white max-[480px]:px-[11px] ${selected ? 'max-[480px]:mr-[-18px] max-[480px]:rounded-r-[15px]' : ''}`} onClick={onSelect}><div className={`grid size-[54px] shrink-0 place-items-center rounded-xl font-display text-[25px] font-extrabold ${iconClass}`} aria-hidden="true">{password.initial}</div><div className="min-w-0 flex-1"><strong className="block text-sm">{password.service}</strong><span className="mt-1 block overflow-hidden text-ellipsis whitespace-nowrap text-[11px] text-[#727891]">{password.account}</span><small className="mt-1 block text-[11px] tracking-[2px] text-[#727891]">******** ◉</small></div><button className="border-0 bg-transparent p-1 text-xl text-[#f62570] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f62570]" type="button" onClick={(event) => { event.stopPropagation(); onToggleFavorite(); }} aria-label={`${password.favorite ? 'Remove' : 'Add'} ${password.service} favorite`} aria-pressed={password.favorite}>{password.favorite ? '♥' : '♡'}</button>{selected && <div className="flex gap-2"><button className="grid size-[34px] place-items-center rounded-full border-0 bg-[#281e3e] text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f62570]" type="button" onClick={(event) => event.stopPropagation()} aria-label={`Edit ${password.service}`}>✎</button><button className="grid size-[34px] place-items-center rounded-full border-0 bg-[#f62570] text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f62570]" type="button" onClick={(event) => { event.stopPropagation(); onDelete(); }} aria-label={`Delete ${password.service}`}>♜</button></div>}</article>;
}

function PasswordFilters({ filter, onFilterChange }: { filter: Filter; onFilterChange: (value: Filter) => void }) {
  return <div className="mb-[21px] flex gap-2 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" role="group" aria-label="Filter passwords">{(['All', 'Recent', 'Favourite', 'Last Edit'] as Filter[]).map((item) => <button className={`shrink-0 rounded-full px-[17px] py-[9px] text-[11px] ${filter === item ? 'bg-linear-to-r from-[#fa3678] to-[#ef4d79] text-white' : 'bg-[#f8f9fb] text-[#172047] hover:bg-[#fff0f5]'} focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f62570]`} key={item} type="button" onClick={() => onFilterChange(item)} aria-pressed={filter === item}>{item}</button>)}</div>;
}

function VaultToolbar({ onAdd }: { onAdd: () => void }) {
  return <div className="mb-[15px] flex items-center justify-between gap-5 min-[481px]:mb-[18px]"><h2 className="font-display text-base min-[481px]:text-lg">All passwords</h2><button className="rounded-[10px] border-0 bg-[#f62570] px-[17px] py-[11px] text-xs font-bold text-white shadow-[0_8px_18px_rgba(246,37,112,0.2)] hover:bg-[#d9185e] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#f62570] max-[480px]:hidden" type="button" onClick={onAdd}>＋ Add password</button></div>;
}

export default function MyVault() {
  const [filter, setFilter] = useState<Filter>('All');
  const [query, setQuery] = useState('');
  const [selectedService, setSelectedService] = useState('Messenger');
  const [passwords, setPasswords] = useState(vaultPasswords);
  const [status, setStatus] = useState('');
  const visiblePasswords = useMemo(() => passwords.filter((password) => { const matchesQuery = `${password.service} ${password.account}`.toLowerCase().includes(query.toLowerCase()); const matchesFilter = filter === 'All' || (filter === 'Favourite' && password.favorite) || (filter === 'Recent' && ['Messenger', 'Gmail'].includes(password.service)) || filter === 'Last Edit'; return matchesQuery && matchesFilter; }), [filter, passwords, query]);
  const toggleFavorite = (service: string) => setPasswords((current) => current.map((password) => password.service === service ? { ...password, favorite: !password.favorite } : password));
  const deletePassword = (service: string) => { setPasswords((current) => current.filter((password) => password.service !== service)); setSelectedService(''); setStatus(`${service} removed from your vault.`); };

  return <div className="flex min-h-screen min-w-[320px] bg-[#dfe5eb] font-sans text-[#172047] max-[840px]:bg-[#f1f5f8]" id="vaults"><Sidebar activeItem="All passwords" /><main className="min-w-0 flex-1 bg-[#f1f5f8] px-[18px] pb-[92px] pt-8 min-[481px]:pt-6 min-[841px]:px-[42px] min-[841px]:pb-[42px] min-[841px]:pt-[35px]"><Header title="My Vaults" onNotify={() => setStatus('You are all caught up.')} /><VaultToolbar onAdd={() => setStatus('Password creation is ready for your next entry.')} /><section className="max-w-[920px] rounded-[20px] border border-[#e5e9f0] bg-white p-[18px] shadow-[0_16px_35px_rgba(24,29,65,0.08)] min-[481px]:p-[25px] max-[480px]:border-0 max-[480px]:bg-transparent max-[480px]:p-0 max-[480px]:shadow-none" aria-labelledby="saved-passwords-title"><h2 className="sr-only" id="saved-passwords-title">Saved passwords</h2><label className="relative mb-[18px] block"><span className="absolute left-[15px] top-1/2 -translate-y-1/2 text-[19px] text-[#727891]" aria-hidden="true">⌕</span><input className="w-full rounded-xl border border-[#e5e9f0] bg-[#fbfcfd] px-4 py-[13px] pl-[43px] text-[#172047] outline-0 focus:border-[#f62570] focus:shadow-[0_0_0_3px_rgba(246,37,112,0.1)] max-[480px]:border-0 max-[480px]:bg-white" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search your vaults" aria-label="Search your vaults" /></label><PasswordFilters filter={filter} onFilterChange={setFilter} /><div className="grid gap-[10px]">{visiblePasswords.map((password) => <PasswordRow key={password.service} password={password} selected={selectedService === password.service} onSelect={() => setSelectedService(password.service)} onToggleFavorite={() => toggleFavorite(password.service)} onDelete={() => deletePassword(password.service)} />)}{visiblePasswords.length === 0 && <p className="py-8 text-center text-sm text-[#727891]">No passwords match your search.</p>}</div><p className="sr-only" role="status" aria-live="polite">{status}</p></section><Footer /></main><MobileNavigation activeItem="Vaults" /></div>;
}
